// Die ersten MVP-Level für SQL Quest. Jedes Level enthält alle Texte für die Oberfläche
// und eine erwartete Abfrage, deren Ergebnis mit der Spieler-Abfrage verglichen wird.
const LEVELS = [
  {
    id: 1,
    title: 'Alle Kunden anzeigen',
    difficulty: 'Anfänger',
    topic: 'SELECT',
    explanation: 'Mit SELECT liest man Daten aus einer Tabelle. Das Sternchen * bedeutet, dass alle Spalten angezeigt werden.',
    task: 'Zeige alle Kunden aus der Tabelle kunden an.',
    expectedSql: 'SELECT * FROM kunden;',
    hint: 'Du brauchst SELECT, das Sternchen * und FROM kunden.',
    points: 10
  },
  {
    id: 2,
    title: 'Nur Namen anzeigen',
    difficulty: 'Anfänger',
    topic: 'Spalten auswählen',
    explanation: 'Man kann gezielt auswählen, welche Spalten angezeigt werden sollen.',
    task: 'Zeige nur die Namen aller Kunden an.',
    expectedSql: 'SELECT name FROM kunden;',
    hint: 'Wenn du nur eine Spalte sehen möchtest, schreibe ihren Namen nach SELECT.',
    points: 10
  },
  {
    id: 3,
    title: 'Kunden aus Berlin finden',
    difficulty: 'Anfänger',
    topic: 'WHERE',
    explanation: 'Mit WHERE filtert man Datensätze.',
    task: 'Zeige alle Kunden an, die aus Berlin kommen.',
    expectedSql: "SELECT * FROM kunden WHERE stadt = 'Berlin';",
    hint: 'Mit WHERE filterst du Zeilen. Textwerte stehen in einfachen Anführungszeichen.',
    points: 10
  },
  {
    id: 4,
    title: 'Nach Punkten sortieren',
    difficulty: 'Anfänger',
    topic: 'ORDER BY',
    explanation: 'Mit ORDER BY sortiert man Ergebnisse. Mit DESC wird absteigend sortiert.',
    task: 'Zeige alle Kunden an, sortiert nach Punkten. Die meisten Punkte sollen oben stehen.',
    expectedSql: 'SELECT * FROM kunden ORDER BY punkte DESC;',
    hint: 'Mit ORDER BY sortierst du. DESC bedeutet absteigend, also die höchsten Werte zuerst.',
    points: 10
  },
  {
    id: 5,
    title: 'Kunden zählen',
    difficulty: 'Anfänger',
    topic: 'COUNT',
    explanation: 'Mit COUNT(*) zählt man Zeilen.',
    task: 'Zähle, wie viele Kunden in der Tabelle gespeichert sind.',
    expectedSql: 'SELECT COUNT(*) FROM kunden;',
    hint: 'COUNT(*) zählt, wie viele Zeilen eine Abfrage zurückgibt.',
    points: 10
  },
  {
    id: 6,
    title: 'Ergebnisse begrenzen',
    difficulty: 'Anfänger',
    topic: 'LIMIT',
    explanation: 'Mit LIMIT begrenzt man, wie viele Zeilen angezeigt werden.',
    task: 'Zeige nur die ersten 3 Kunden aus der Tabelle kunden an.',
    expectedSql: 'SELECT * FROM kunden LIMIT 3;',
    hint: 'Schreibe LIMIT 3 ans Ende deiner SELECT-Abfrage.',
    points: 10
  },
  {
    id: 7,
    title: 'Vergleichsoperator größer als',
    difficulty: 'Anfänger',
    topic: 'Vergleichsoperatoren',
    explanation: 'Mit Vergleichsoperatoren wie >, < oder = kann man Zahlenwerte filtern.',
    task: 'Zeige alle Kunden an, die mehr als 100 Punkte haben.',
    expectedSql: 'SELECT * FROM kunden WHERE punkte > 100;',
    hint: 'Nutze WHERE und den Vergleich punkte > 100.',
    points: 10
  },
  {
    id: 8,
    title: 'Textsuche mit LIKE',
    difficulty: 'Anfänger',
    topic: 'LIKE',
    explanation: 'Mit LIKE kann man nach Textmustern suchen. Das Prozentzeichen % steht für beliebige weitere Zeichen.',
    task: 'Zeige alle Kunden an, deren Name mit A beginnt.',
    expectedSql: "SELECT * FROM kunden WHERE name LIKE 'A%';",
    hint: 'A% bedeutet: Der Text beginnt mit A und danach kann beliebiger Text folgen.',
    points: 10
  },
  {
    id: 9,
    title: 'Mehrere Bedingungen mit AND',
    difficulty: 'Anfänger',
    topic: 'AND',
    explanation: 'Mit AND müssen mehrere Bedingungen gleichzeitig erfüllt sein.',
    task: 'Zeige alle Kunden aus Berlin an, die mehr als 100 Punkte haben.',
    expectedSql: "SELECT * FROM kunden WHERE stadt = 'Berlin' AND punkte > 100;",
    hint: 'Verbinde die Bedingung für stadt mit der Bedingung für punkte durch AND.',
    points: 10
  },
  {
    id: 10,
    title: 'Durchschnitt berechnen',
    difficulty: 'Anfänger',
    topic: 'AVG',
    explanation: 'Mit AVG berechnet man den Durchschnitt einer Zahlenspalte.',
    task: 'Berechne das durchschnittliche Alter aller Kunden.',
    expectedSql: 'SELECT AVG(alter_jahre) FROM kunden;',
    hint: 'AVG(alter_jahre) berechnet den Durchschnitt der Spalte alter_jahre.',
    points: 10
  },
  {
    id: 11,
    title: 'Bedingungen mit OR',
    difficulty: 'Anfänger',
    topic: 'OR',
    explanation: 'Mit OR genügt es, wenn mindestens eine von mehreren Bedingungen erfüllt ist.',
    task: 'Zeige alle Kunden aus Berlin oder Hamburg an.',
    expectedSql: "SELECT * FROM kunden WHERE stadt = 'Berlin' OR stadt = 'Hamburg';",
    hint: 'Verbinde beide Stadt-Bedingungen mit OR.',
    points: 10
  },
  {
    id: 12,
    title: 'Jünger als 30',
    difficulty: 'Anfänger',
    topic: '<',
    explanation: 'Mit < findest du Werte, die kleiner als ein bestimmter Wert sind.',
    task: 'Zeige alle Kunden an, die jünger als 30 Jahre sind.',
    expectedSql: 'SELECT * FROM kunden WHERE alter_jahre < 30;',
    hint: 'Filtere die Spalte alter_jahre mit dem Vergleich < 30.',
    points: 10
  },
  {
    id: 13,
    title: 'Mindestens 120 Punkte',
    difficulty: 'Anfänger',
    topic: '>=',
    explanation: 'Mit >= findest du Werte, die größer oder gleich einem bestimmten Wert sind.',
    task: 'Zeige alle Kunden an, die mindestens 120 Punkte haben.',
    expectedSql: 'SELECT * FROM kunden WHERE punkte >= 120;',
    hint: '„Mindestens“ bedeutet: größer oder gleich. Nutze >=.',
    points: 10
  },
  {
    id: 14,
    title: 'Höchstens 100 Punkte',
    difficulty: 'Anfänger',
    topic: '<=',
    explanation: 'Mit <= findest du Werte, die kleiner oder gleich einem bestimmten Wert sind.',
    task: 'Zeige alle Kunden an, die höchstens 100 Punkte haben.',
    expectedSql: 'SELECT * FROM kunden WHERE punkte <= 100;',
    hint: '„Höchstens“ bedeutet: kleiner oder gleich. Nutze <=.',
    points: 10
  },
  {
    id: 15,
    title: 'Ausschließen mit NOT',
    difficulty: 'Anfänger',
    topic: 'NOT',
    explanation: 'Mit NOT kannst du Bedingungen ausschließen.',
    task: 'Zeige alle Kunden an, die nicht aus Berlin kommen.',
    expectedSql: "SELECT * FROM kunden WHERE NOT stadt = 'Berlin';",
    hint: "Setze NOT vor die Bedingung stadt = 'Berlin'.",
    points: 10
  },
  {
    id: 16,
    title: 'Punkte zusammenzählen',
    difficulty: 'Anfänger',
    topic: 'SUM',
    explanation: 'Mit SUM kannst du Zahlenwerte einer Spalte zusammenzählen.',
    task: 'Berechne die Summe aller Punkte aller Kunden.',
    expectedSql: 'SELECT SUM(punkte) FROM kunden;',
    hint: 'Nutze SUM mit der Spalte punkte.',
    points: 10
  },
  {
    id: 17,
    title: 'Jüngster Kunde',
    difficulty: 'Anfänger',
    topic: 'MIN',
    explanation: 'Mit MIN findest du den kleinsten Wert einer Spalte.',
    task: 'Finde das niedrigste Alter aller Kunden.',
    expectedSql: 'SELECT MIN(alter_jahre) FROM kunden;',
    hint: 'Nutze MIN mit der Spalte alter_jahre.',
    points: 10
  },
  {
    id: 18,
    title: 'Höchste Punktzahl',
    difficulty: 'Anfänger',
    topic: 'MAX',
    explanation: 'Mit MAX findest du den größten Wert einer Spalte.',
    task: 'Finde die höchste Punktzahl aller Kunden.',
    expectedSql: 'SELECT MAX(punkte) FROM kunden;',
    hint: 'Nutze MAX mit der Spalte punkte.',
    points: 10
  },
  {
    id: 19,
    title: 'Städte ohne Wiederholungen',
    difficulty: 'Anfänger',
    topic: 'DISTINCT',
    explanation: 'Mit DISTINCT werden doppelte Werte nur einmal angezeigt.',
    task: 'Zeige alle Städte an, in denen Kunden wohnen. Jede Stadt soll nur einmal erscheinen.',
    expectedSql: 'SELECT DISTINCT stadt FROM kunden;',
    hint: 'Setze DISTINCT direkt nach SELECT vor die Spalte stadt.',
    points: 10
  },
  {
    id: 20,
    title: 'Top-Kunden',
    difficulty: 'Anfänger',
    topic: 'WHERE + ORDER BY + LIMIT',
    explanation: 'Du kannst Filtern, Sortieren und Begrenzen in einer Abfrage kombinieren.',
    task: 'Zeige die drei Kunden mit mindestens 100 Punkten an. Sortiere sie absteigend nach Punkten.',
    expectedSql: 'SELECT * FROM kunden WHERE punkte >= 100 ORDER BY punkte DESC LIMIT 3;',
    hint: 'Nutze zuerst WHERE, danach ORDER BY punkte DESC und am Ende LIMIT 3.',
    points: 10
  },
  {
    id: 21,
    title: 'Berliner Kunden mit Punkten',
    difficulty: 'Anfänger',
    topic: 'WHERE + AND',
    explanation: 'Mit AND kannst du mehrere Bedingungen gleichzeitig prüfen.',
    task: 'Zeige alle Kunden aus Berlin an, die mindestens 100 Punkte haben.',
    expectedSql: "SELECT * FROM kunden WHERE stadt = 'Berlin' AND punkte >= 100;",
    hint: 'Verbinde die Stadt-Bedingung und die Punkte-Bedingung mit AND.',
    points: 10
  },
  {
    id: 22,
    title: 'Namen und Punkte sortieren',
    difficulty: 'Anfänger',
    topic: 'SELECT + ORDER BY',
    explanation: 'Du kannst bestimmte Spalten auswählen und die Ergebnisse sortieren.',
    task: 'Zeige den Namen und die Punkte aller Kunden an. Sortiere absteigend nach Punkten.',
    expectedSql: 'SELECT name, punkte FROM kunden ORDER BY punkte DESC;',
    hint: 'Wähle zuerst name und punkte aus. Sortiere danach mit ORDER BY punkte DESC.',
    points: 10
  },
  {
    id: 23,
    title: 'Städte alphabetisch anzeigen',
    difficulty: 'Anfänger',
    topic: 'DISTINCT + ORDER BY',
    explanation: 'DISTINCT entfernt Wiederholungen und ORDER BY sortiert das Ergebnis.',
    task: 'Zeige alle Städte ohne Wiederholungen alphabetisch an.',
    expectedSql: 'SELECT DISTINCT stadt FROM kunden ORDER BY stadt ASC;',
    hint: 'Nutze DISTINCT für stadt und sortiere danach mit ORDER BY stadt ASC.',
    points: 10
  },
  {
    id: 24,
    title: 'Durchschnittliche Punkte',
    difficulty: 'Anfänger',
    topic: 'AVG',
    explanation: 'Mit AVG kannst du den Durchschnitt einer Zahlenspalte berechnen.',
    task: 'Berechne die durchschnittliche Punktzahl aller Kunden.',
    expectedSql: 'SELECT AVG(punkte) FROM kunden;',
    hint: 'Nutze AVG mit der Spalte punkte.',
    points: 10
  },
  {
    id: 25,
    title: 'Abschluss-Challenge Top-Kunden',
    difficulty: 'Anfänger',
    topic: 'WHERE + ORDER BY + LIMIT',
    explanation: 'In einer SQL-Abfrage kannst du filtern, sortieren und die Anzahl der Ergebnisse begrenzen.',
    task: 'Zeige die zwei Kunden mit mindestens 80 Punkten an. Sortiere sie absteigend nach Punkten.',
    expectedSql: 'SELECT * FROM kunden WHERE punkte >= 80 ORDER BY punkte DESC LIMIT 2;',
    hint: 'Nutze zuerst WHERE, danach ORDER BY punkte DESC und am Ende LIMIT 2.',
    points: 10
  },
  {
    id: 26,
    title: 'Kunden pro Stadt zählen',
    difficulty: 'Anfänger',
    topic: 'GROUP BY + COUNT',
    explanation: 'GROUP BY fasst Zeilen mit dem gleichen Wert zusammen. So werden alle Kunden aus derselben Stadt zu einer Gruppe zusammengefasst.',
    task: 'Zeige jede Stadt und die Anzahl der Kunden aus dieser Stadt.',
    expectedSql: 'SELECT stadt, COUNT(*) FROM kunden GROUP BY stadt;',
    hint: 'GROUP BY fasst Zeilen mit dem gleichen Wert zusammen. Gruppiere nach stadt und zähle jede Gruppe mit COUNT(*).',
    points: 10
  },
  {
    id: 27,
    title: 'Punkte pro Stadt berechnen',
    difficulty: 'Anfänger',
    topic: 'GROUP BY + SUM',
    explanation: 'Mit GROUP BY kannst du gleiche Städte zusammenfassen und jede Gruppe mit SUM auswerten.',
    task: 'Zeige jede Stadt und die Summe aller Punkte ihrer Kunden.',
    expectedSql: 'SELECT stadt, SUM(punkte) FROM kunden GROUP BY stadt;',
    hint: 'GROUP BY fasst Zeilen mit dem gleichen Wert zusammen. Nutze SUM(punkte), um die Punkte pro Stadt zu addieren.',
    points: 10
  },
  {
    id: 28,
    title: 'Durchschnittliche Punkte pro Stadt',
    difficulty: 'Anfänger',
    topic: 'GROUP BY + AVG',
    explanation: 'Mit AVG wertest du Zahlenspalten aus. Zusammen mit GROUP BY berechnest du den Durchschnitt pro Gruppe.',
    task: 'Zeige jede Stadt und den durchschnittlichen Punktestand ihrer Kunden.',
    expectedSql: 'SELECT stadt, AVG(punkte) FROM kunden GROUP BY stadt;',
    hint: 'Gruppiere nach stadt und berechne mit AVG(punkte) den Durchschnitt für jede Stadt.',
    points: 10
  },
  {
    id: 29,
    title: 'Städte mit mehreren Kunden',
    difficulty: 'Anfänger',
    topic: 'GROUP BY + HAVING',
    explanation: 'HAVING filtert Gruppen. WHERE filtert einzelne Zeilen vor dem Gruppieren, HAVING filtert Gruppen nach GROUP BY.',
    task: 'Zeige nur Städte, in denen mehr als ein Kunde lebt. Gib Stadt und Anzahl der Kunden aus.',
    expectedSql: 'SELECT stadt, COUNT(*) FROM kunden GROUP BY stadt HAVING COUNT(*) > 1;',
    hint: 'HAVING filtert Gruppen. Nutze HAVING COUNT(*) > 1 nach GROUP BY.',
    points: 10
  },
  {
    id: 30,
    title: 'Stadt mit den meisten Punkten',
    difficulty: 'Anfänger',
    topic: 'GROUP BY + ORDER BY + LIMIT',
    explanation: 'Du kannst Gruppen auswerten, die Gruppenergebnisse sortieren und mit LIMIT nur die beste Gruppe anzeigen.',
    task: 'Zeige die Stadt mit der höchsten Summe an Kundenpunkten.',
    expectedSql: 'SELECT stadt, SUM(punkte) FROM kunden GROUP BY stadt ORDER BY SUM(punkte) DESC LIMIT 1;',
    hint: 'Gruppiere nach stadt, addiere SUM(punkte), sortiere absteigend und begrenze das Ergebnis mit LIMIT 1.',
    points: 10

  },
  {
    id: 31,
    title: 'Kunden und Bestellungen verbinden',
    difficulty: 'Fortgeschritten',
    topic: 'INNER JOIN',
    explanation: 'Ein JOIN verbindet Zeilen aus zwei Tabellen. Mit INNER JOIN erscheinen nur passende Zeilen aus beiden Tabellen.',
    task: 'Zeige Kundennamen und Bestelldatum, indem du kunden mit bestellungen verbindest.',
    expectedSql: 'SELECT kunden.name, bestellungen.bestelldatum FROM kunden INNER JOIN bestellungen ON kunden.id = bestellungen.kunden_id;',
    hint: 'Verbinde kunden.id mit bestellungen.kunden_id in der ON-Bedingung.',
    points: 15
  },
  {
    id: 32,
    title: 'Bestellungen mit Status anzeigen',
    difficulty: 'Fortgeschritten',
    topic: 'INNER JOIN',
    explanation: 'Die ON-Bedingung beschreibt, welche Schlüssel zusammengehören.',
    task: 'Zeige Kundennamen, Bestelldatum und Status aller Bestellungen.',
    expectedSql: 'SELECT kunden.name, bestellungen.bestelldatum, bestellungen.status FROM kunden INNER JOIN bestellungen ON kunden.id = bestellungen.kunden_id;',
    hint: 'Wähle Spalten aus beiden Tabellen und verbinde über kunden.id = bestellungen.kunden_id.',
    points: 15
  },
  {
    id: 33,
    title: 'Spalten aus zwei Tabellen auswählen',
    difficulty: 'Fortgeschritten',
    topic: 'JOIN + Spalten',
    explanation: 'Bei verbundenen Tabellen kannst du gezielt Spalten aus jeder beteiligten Tabelle auswählen.',
    task: 'Zeige Bestell-ID, Kundenname und Bestellstatus für alle Bestellungen.',
    expectedSql: 'SELECT bestellungen.id, kunden.name, bestellungen.status FROM bestellungen INNER JOIN kunden ON bestellungen.kunden_id = kunden.id;',
    hint: 'Starte bei bestellungen und verbinde kunden über bestellungen.kunden_id = kunden.id.',
    points: 15
  },
  {
    id: 34,
    title: 'JOIN mit WHERE filtern',
    difficulty: 'Fortgeschritten',
    topic: 'JOIN + WHERE',
    explanation: 'Nach einem JOIN kannst du das verbundene Ergebnis mit WHERE filtern.',
    task: 'Zeige Kundennamen und Bestelldatum aller bezahlten Bestellungen.',
    expectedSql: "SELECT kunden.name, bestellungen.bestelldatum FROM kunden INNER JOIN bestellungen ON kunden.id = bestellungen.kunden_id WHERE bestellungen.status = 'bezahlt';",
    hint: "Filtere nach dem JOIN mit WHERE bestellungen.status = 'bezahlt'.",
    points: 15
  },
  {
    id: 35,
    title: 'JOIN mit ORDER BY sortieren',
    difficulty: 'Fortgeschritten',
    topic: 'JOIN + ORDER BY',
    explanation: 'ORDER BY sortiert auch Ergebnisse, die aus mehreren Tabellen zusammengesetzt wurden.',
    task: 'Zeige Kundennamen und Bestelldatum aller Bestellungen, sortiert nach Bestelldatum absteigend.',
    expectedSql: 'SELECT kunden.name, bestellungen.bestelldatum FROM kunden INNER JOIN bestellungen ON kunden.id = bestellungen.kunden_id ORDER BY bestellungen.bestelldatum DESC;',
    hint: 'Setze ORDER BY bestellungen.bestelldatum DESC ans Ende.',
    points: 15
  },
  {
    id: 36,
    title: 'Alle Kunden mit Bestellungen anzeigen',
    difficulty: 'Fortgeschritten',
    topic: 'LEFT JOIN',
    explanation: 'LEFT JOIN zeigt alle Zeilen der linken Tabelle und ergänzt passende Zeilen der rechten Tabelle. Fehlt rechts ein Treffer, stehen dort leere Werte.',
    task: 'Zeige alle Kundennamen und ihre Bestelldaten. Auch Kunden ohne Bestellung sollen erscheinen.',
    expectedSql: 'SELECT kunden.name, bestellungen.bestelldatum FROM kunden LEFT JOIN bestellungen ON kunden.id = bestellungen.kunden_id;',
    hint: 'Nutze kunden als linke Tabelle und LEFT JOIN bestellungen.',
    points: 15
  },
  {
    id: 37,
    title: 'Kunden ohne Bestellung finden',
    difficulty: 'Fortgeschritten',
    topic: 'LEFT JOIN + WHERE',
    explanation: 'Mit LEFT JOIN und einem NULL-Filter findest du Zeilen der linken Tabelle ohne passenden Eintrag rechts.',
    task: 'Zeige die Namen aller Kunden, die keine Bestellung haben.',
    expectedSql: 'SELECT kunden.name FROM kunden LEFT JOIN bestellungen ON kunden.id = bestellungen.kunden_id WHERE bestellungen.id IS NULL;',
    hint: 'Nach dem LEFT JOIN prüfst du WHERE bestellungen.id IS NULL.',
    points: 15
  },
  {
    id: 38,
    title: 'Bestellungen und Positionen verbinden',
    difficulty: 'Fortgeschritten',
    topic: 'Mehrere Tabellen',
    explanation: 'Bestellungen und bestellpositionen hängen über bestellungen.id und bestellpositionen.bestellung_id zusammen.',
    task: 'Zeige Bestell-ID, Positions-ID und Menge für alle Bestellpositionen.',
    expectedSql: 'SELECT bestellungen.id, bestellpositionen.id, bestellpositionen.menge FROM bestellungen INNER JOIN bestellpositionen ON bestellungen.id = bestellpositionen.bestellung_id;',
    hint: 'Verbinde bestellungen.id mit bestellpositionen.bestellung_id.',
    points: 15
  },
  {
    id: 39,
    title: 'Produkte über Bestellpositionen einbeziehen',
    difficulty: 'Fortgeschritten',
    topic: 'Drei Tabellen',
    explanation: 'Über bestellpositionen.produkt_id erreichst du die Produktdaten einer Position.',
    task: 'Zeige Bestell-ID, Produktname und Menge für alle Bestellpositionen.',
    expectedSql: 'SELECT bestellungen.id, produkte.name, bestellpositionen.menge FROM bestellungen INNER JOIN bestellpositionen ON bestellungen.id = bestellpositionen.bestellung_id INNER JOIN produkte ON bestellpositionen.produkt_id = produkte.id;',
    hint: 'Verbinde erst Bestellungen mit Positionen und dann Positionen mit Produkten.',
    points: 15
  },
  {
    id: 40,
    title: 'Shop-Auswertung über mehrere Tabellen',
    difficulty: 'Fortgeschritten',
    topic: 'JOIN + Berechnung',
    explanation: 'Mit mehreren JOINs kannst du eine vollständige Shop-Auswertung erstellen und Werte aus verbundenen Tabellen berechnen.',
    task: 'Zeige Kundenname, Bestell-ID, Produktname, Menge und Positionswert für jede Bestellposition. Sortiere nach Bestell-ID und Produktname.',
    expectedSql: 'SELECT kunden.name, bestellungen.id, produkte.name, bestellpositionen.menge, bestellpositionen.menge * bestellpositionen.einzelpreis FROM kunden INNER JOIN bestellungen ON kunden.id = bestellungen.kunden_id INNER JOIN bestellpositionen ON bestellungen.id = bestellpositionen.bestellung_id INNER JOIN produkte ON bestellpositionen.produkt_id = produkte.id ORDER BY bestellungen.id ASC, produkte.name ASC;',
    hint: 'Verbinde kunden → bestellungen → bestellpositionen → produkte und berechne menge * einzelpreis.',
    points: 15
  },
  {
    id: 41,
    title: 'Bestellungen pro Kunde zählen',
    difficulty: 'Fortgeschritten',
    topic: 'COUNT() mit JOIN',
    explanation: 'Mit COUNT() und LEFT JOIN kannst du auch Kunden ohne Bestellung mitzählen, weil alle Kunden aus der linken Tabelle erhalten bleiben.',
    task: 'Zeige jeden Kundennamen und die Anzahl seiner Bestellungen.',
    expectedSql: 'SELECT kunden.name, COUNT(bestellungen.id) FROM kunden LEFT JOIN bestellungen ON kunden.id = bestellungen.kunden_id GROUP BY kunden.name;',
    hint: 'Nutze LEFT JOIN von kunden zu bestellungen und gruppiere nach kunden.name.',
    points: 15
  },
  {
    id: 42,
    title: 'Positionen pro Bestellung zählen',
    difficulty: 'Fortgeschritten',
    topic: 'COUNT() mit JOIN',
    explanation: 'COUNT(bestellpositionen.id) zählt pro gruppierter Bestellung, wie viele Positionen über den JOIN gefunden wurden.',
    task: 'Zeige jede Bestell-ID und die Anzahl ihrer Bestellpositionen.',
    expectedSql: 'SELECT bestellungen.id, COUNT(bestellpositionen.id) FROM bestellungen LEFT JOIN bestellpositionen ON bestellungen.id = bestellpositionen.bestellung_id GROUP BY bestellungen.id;',
    hint: 'Verbinde bestellungen per LEFT JOIN mit bestellpositionen und gruppiere nach bestellungen.id.',
    points: 15
  },
  {
    id: 43,
    title: 'Bestellwert pro Bestellung berechnen',
    difficulty: 'Fortgeschritten',
    topic: 'SUM() mit JOIN',
    explanation: 'SUM() addiert berechnete Positionswerte. Der Bestellwert entsteht aus menge * einzelpreis je Position.',
    task: 'Zeige jede Bestell-ID und ihren Bestellwert.',
    expectedSql: 'SELECT bestellungen.id, SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) FROM bestellungen INNER JOIN bestellpositionen ON bestellungen.id = bestellpositionen.bestellung_id GROUP BY bestellungen.id;',
    hint: 'Berechne SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) je bestellungen.id.',
    points: 15
  },
  {
    id: 44,
    title: 'Gesamtumsatz pro Kunde',
    difficulty: 'Fortgeschritten',
    topic: 'SUM() mit JOIN',
    explanation: 'Für Umsätze pro Kunde verbindest du kunden, bestellungen und bestellpositionen und summierst die Positionswerte je Kunde.',
    task: 'Zeige jeden Kundennamen mit seinem Gesamtumsatz aus allen Bestellpositionen.',
    expectedSql: 'SELECT kunden.name, SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) FROM kunden INNER JOIN bestellungen ON kunden.id = bestellungen.kunden_id INNER JOIN bestellpositionen ON bestellungen.id = bestellpositionen.bestellung_id GROUP BY kunden.name;',
    hint: 'Verbinde kunden → bestellungen → bestellpositionen und gruppiere nach kunden.name.',
    points: 15
  },
  {
    id: 45,
    title: 'Verkaufte Menge pro Produkt',
    difficulty: 'Fortgeschritten',
    topic: 'SUM() mit JOIN',
    explanation: 'Mit GROUP BY über Produktnamen und SUM(menge) ermittelst du, wie oft jedes Produkt verkauft wurde.',
    task: 'Zeige jeden Produktnamen und die insgesamt verkaufte Menge.',
    expectedSql: 'SELECT produkte.name, SUM(bestellpositionen.menge) FROM produkte INNER JOIN bestellpositionen ON produkte.id = bestellpositionen.produkt_id GROUP BY produkte.name;',
    hint: 'Verbinde produkte mit bestellpositionen und summiere bestellpositionen.menge pro Produkt.',
    points: 15
  },
  {
    id: 46,
    title: 'Kunden nach Umsatz sortieren',
    difficulty: 'Fortgeschritten',
    topic: 'GROUP BY + ORDER BY mit JOIN',
    explanation: 'ORDER BY kann gruppierte JOIN-Ergebnisse nach einem Aggregat wie SUM() sortieren.',
    task: 'Zeige Kundennamen und Gesamtumsatz, sortiert nach Gesamtumsatz absteigend.',
    expectedSql: 'SELECT kunden.name, SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) FROM kunden INNER JOIN bestellungen ON kunden.id = bestellungen.kunden_id INNER JOIN bestellpositionen ON bestellungen.id = bestellpositionen.bestellung_id GROUP BY kunden.name ORDER BY SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) DESC;',
    hint: 'Gruppiere nach kunden.name und sortiere mit ORDER BY SUM(...) DESC.',
    points: 15
  },
  {
    id: 47,
    title: 'Produkte nach verkaufter Menge sortieren',
    difficulty: 'Fortgeschritten',
    topic: 'GROUP BY + ORDER BY mit JOIN',
    explanation: 'Du kannst Produktgruppen nach ihrer verkauften Gesamtmenge sortieren.',
    task: 'Zeige Produktnamen und verkaufte Gesamtmenge, sortiert nach Menge absteigend.',
    expectedSql: 'SELECT produkte.name, SUM(bestellpositionen.menge) FROM produkte INNER JOIN bestellpositionen ON produkte.id = bestellpositionen.produkt_id GROUP BY produkte.name ORDER BY SUM(bestellpositionen.menge) DESC;',
    hint: 'Sortiere nach SUM(bestellpositionen.menge) DESC.',
    points: 15
  },
  {
    id: 48,
    title: 'Bestellungen nach Bestellwert sortieren',
    difficulty: 'Fortgeschritten',
    topic: 'GROUP BY + ORDER BY mit JOIN',
    explanation: 'Wenn du je Bestellung summierst, kannst du die Bestellungen anschließend nach ihrem Bestellwert sortieren.',
    task: 'Zeige Bestell-ID und Bestellwert, sortiert nach Bestellwert absteigend.',
    expectedSql: 'SELECT bestellungen.id, SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) FROM bestellungen INNER JOIN bestellpositionen ON bestellungen.id = bestellpositionen.bestellung_id GROUP BY bestellungen.id ORDER BY SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) DESC;',
    hint: 'Gruppiere nach bestellungen.id und sortiere nach dem berechneten SUM-Ausdruck absteigend.',
    points: 15
  },
  {
    id: 49,
    title: 'Kunden mit mehreren Bestellungen',
    difficulty: 'Fortgeschritten',
    topic: 'HAVING mit JOIN',
    explanation: 'HAVING filtert nach dem Gruppieren. Nutze es hier für die Bedingung auf COUNT(bestellungen.id).',
    task: 'Zeige Kundennamen und Bestellanzahl für Kunden mit mehr als einer Bestellung.',
    expectedSql: 'SELECT kunden.name, COUNT(bestellungen.id) FROM kunden INNER JOIN bestellungen ON kunden.id = bestellungen.kunden_id GROUP BY kunden.name HAVING COUNT(bestellungen.id) > 1;',
    hint: 'Gruppiere nach kunden.name und filtere mit HAVING COUNT(bestellungen.id) > 1.',
    points: 15
  },
  {
    id: 50,
    title: 'Produkte mit hoher Verkaufsmenge',
    difficulty: 'Fortgeschritten',
    topic: 'HAVING mit JOIN',
    explanation: 'HAVING ist richtig, wenn die Bedingung eine gruppierte Summe wie SUM(menge) betrifft.',
    task: 'Zeige Produktnamen und verkaufte Gesamtmenge für Produkte, die insgesamt mehr als 2 Stück verkauft wurden.',
    expectedSql: 'SELECT produkte.name, SUM(bestellpositionen.menge) FROM produkte INNER JOIN bestellpositionen ON produkte.id = bestellpositionen.produkt_id GROUP BY produkte.name HAVING SUM(bestellpositionen.menge) > 2;',
    hint: 'Nutze HAVING SUM(bestellpositionen.menge) > 2 nach GROUP BY.',
    points: 15
  },
  {
    id: 51,
    title: 'Kunden mit Bestellung per IN',
    difficulty: 'Fortgeschritten',
    topic: 'IN mit Unterabfrage',
    explanation: 'Eine Unterabfrage liefert eine Liste von Werten. Mit IN prüfst du, ob ein Wert in dieser Liste vorkommt.',
    task: 'Zeige die Namen aller Kunden, die mindestens eine Bestellung haben.',
    expectedSql: 'SELECT name FROM kunden WHERE id IN (SELECT kunden_id FROM bestellungen);',
    hint: 'Die Unterabfrage SELECT kunden_id FROM bestellungen liefert alle Kunden-IDs mit Bestellung.',
    points: 15
  },
  {
    id: 52,
    title: 'Kunden ohne Bestellung per NOT IN',
    difficulty: 'Fortgeschritten',
    topic: 'NOT IN mit Unterabfrage',
    explanation: 'NOT IN schließt alle Werte aus, die in der Ergebnisliste einer Unterabfrage vorkommen.',
    task: 'Zeige die Namen aller Kunden, die keine Bestellung haben.',
    expectedSql: 'SELECT name FROM kunden WHERE id NOT IN (SELECT kunden_id FROM bestellungen);',
    hint: 'Suche Kunden-IDs, die nicht in den kunden_id-Werten der Tabelle bestellungen stehen.',
    points: 15
  },
  {
    id: 53,
    title: 'Produkte über Durchschnittspreis',
    difficulty: 'Fortgeschritten',
    topic: 'Unterabfrage mit AVG()',
    explanation: 'Eine Unterabfrage kann einen einzelnen Vergleichswert berechnen, zum Beispiel den Durchschnittspreis aller Produkte.',
    task: 'Zeige Produktnamen und Preise aller Produkte, die teurer als der Durchschnittspreis sind.',
    expectedSql: 'SELECT name, preis FROM produkte WHERE preis > (SELECT AVG(preis) FROM produkte);',
    hint: 'Vergleiche preis mit einer Unterabfrage, die AVG(preis) aus produkte berechnet.',
    points: 15
  },
  {
    id: 54,
    title: 'Produkte unter Durchschnittspreis',
    difficulty: 'Fortgeschritten',
    topic: 'Unterabfrage mit AVG()',
    explanation: 'Mit demselben Durchschnittswert kannst du auch die günstigeren Produkte herausfiltern.',
    task: 'Zeige Produktnamen und Preise aller Produkte, die günstiger als der Durchschnittspreis sind.',
    expectedSql: 'SELECT name, preis FROM produkte WHERE preis < (SELECT AVG(preis) FROM produkte);',
    hint: 'Nutze preis < (SELECT AVG(preis) FROM produkte).',
    points: 15
  },
  {
    id: 55,
    title: 'Mehrfachbesteller per Unterabfrage',
    difficulty: 'Fortgeschritten',
    topic: 'Unterabfrage mit GROUP BY und HAVING',
    explanation: 'GROUP BY und HAVING können in einer Unterabfrage eine Liste von IDs liefern, die eine Aggregatbedingung erfüllen.',
    task: 'Zeige die Namen aller Kunden, die mehr als eine Bestellung haben.',
    expectedSql: 'SELECT name FROM kunden WHERE id IN (SELECT kunden_id FROM bestellungen GROUP BY kunden_id HAVING COUNT(*) > 1);',
    hint: 'Gruppiere bestellungen nach kunden_id und filtere Gruppen mit HAVING COUNT(*) > 1.',
    points: 15
  },
  {
    id: 56,
    title: 'Produkte mit überdurchschnittlicher Verkaufsmenge',
    difficulty: 'Fortgeschritten',
    topic: 'Unterabfrage mit GROUP BY und HAVING',
    explanation: 'Eine gruppierte Unterabfrage kann verkaufte Mengen pro Produkt mit der durchschnittlichen Positionsmenge vergleichen.',
    task: 'Zeige Produktnamen und verkaufte Gesamtmenge für Produkte, deren Gesamtmenge über der durchschnittlichen Menge pro Bestellposition liegt.',
    expectedSql: 'SELECT produkte.name, SUM(bestellpositionen.menge) FROM produkte INNER JOIN bestellpositionen ON produkte.id = bestellpositionen.produkt_id GROUP BY produkte.name HAVING SUM(bestellpositionen.menge) > (SELECT AVG(menge) FROM bestellpositionen);',
    hint: 'Verbinde produkte mit bestellpositionen, gruppiere nach produkte.name und vergleiche SUM(menge) mit SELECT AVG(menge).',
    points: 15
  },
  {
    id: 57,
    title: 'Kunden mit Bestellung per EXISTS',
    difficulty: 'Fortgeschritten',
    topic: 'EXISTS',
    explanation: 'EXISTS prüft, ob eine passende Zeile in einer Unterabfrage existiert. Die Unterabfrage bezieht sich dabei auf die aktuelle Zeile der äußeren Abfrage.',
    task: 'Zeige die Namen aller Kunden, für die mindestens eine Bestellung existiert.',
    expectedSql: 'SELECT kunden.name FROM kunden WHERE EXISTS (SELECT 1 FROM bestellungen WHERE bestellungen.kunden_id = kunden.id);',
    hint: 'In der Unterabfrage vergleichst du bestellungen.kunden_id mit kunden.id der äußeren Abfrage.',
    points: 15
  },
  {
    id: 58,
    title: 'Kunden ohne Bestellung per NOT EXISTS',
    difficulty: 'Fortgeschritten',
    topic: 'NOT EXISTS',
    explanation: 'NOT EXISTS findet Zeilen, für die keine passende Zeile in der Unterabfrage existiert.',
    task: 'Zeige die Namen aller Kunden, für die keine Bestellung existiert.',
    expectedSql: 'SELECT kunden.name FROM kunden WHERE NOT EXISTS (SELECT 1 FROM bestellungen WHERE bestellungen.kunden_id = kunden.id);',
    hint: 'Nutze NOT EXISTS mit derselben Beziehung bestellungen.kunden_id = kunden.id.',
    points: 15
  },
  {
    id: 59,
    title: 'Kundenumsatz über Durchschnittsbestellwert',
    difficulty: 'Fortgeschritten',
    topic: 'JOIN + GROUP BY + Unterabfrage',
    explanation: 'Komplexere Auswertungen kombinieren JOINs, Bestellwertberechnung, GROUP BY und eine Unterabfrage mit Durchschnittswert.',
    task: 'Zeige Kundennamen und Gesamtumsatz für Kunden, deren Gesamtumsatz größer als der durchschnittliche Bestellwert ist.',
    expectedSql: 'SELECT kunden.name, SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) FROM kunden INNER JOIN bestellungen ON kunden.id = bestellungen.kunden_id INNER JOIN bestellpositionen ON bestellungen.id = bestellpositionen.bestellung_id GROUP BY kunden.name HAVING SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) > (SELECT AVG(bestellwert) FROM (SELECT SUM(menge * einzelpreis) AS bestellwert FROM bestellpositionen GROUP BY bestellung_id));',
    hint: 'Berechne außen den Umsatz pro Kunde und innen den durchschnittlichen Wert gruppierter Bestellungen.',
    points: 15
  },
  {
    id: 60,
    title: 'Bestellte Produkte über Durchschnittspreis',
    difficulty: 'Fortgeschritten',
    topic: 'JOIN + EXISTS + AVG()',
    explanation: 'Diese Abfrage kombiniert eine Preis-Unterabfrage mit EXISTS, um nur Produkte zu zeigen, die auch wirklich bestellt wurden.',
    task: 'Zeige Produktnamen und Preise aller Produkte, die teurer als der Durchschnittspreis sind und mindestens einmal bestellt wurden.',
    expectedSql: 'SELECT produkte.name, produkte.preis FROM produkte WHERE produkte.preis > (SELECT AVG(preis) FROM produkte) AND EXISTS (SELECT 1 FROM bestellpositionen WHERE bestellpositionen.produkt_id = produkte.id);',
    hint: 'Kombiniere den AVG(preis)-Vergleich mit EXISTS auf bestellpositionen.produkt_id = produkte.id.',
    points: 15

  },
  {
    id: 61,
    title: 'Kundenumsätze einordnen',
    difficulty: 'Meister',
    topic: 'CASE WHEN',
    explanation: 'Mit CASE WHEN ordnest du berechnete Werte in lesbare Kategorien ein. So wird aus einem Zahlenwert eine verständliche Bewertung.',
    task: 'Berechne den Umsatz pro Kunde und teile ihn in Umsatzkategorien ein: Hoch ab 500, Mittel ab 50, sonst Niedrig. Zeige nur Kunden mit Bestellungen.',
    expectedSql: `SELECT kunden.name, SUM(bestellpositionen.menge * bestellpositionen.einzelpreis), CASE WHEN SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) >= 500 THEN 'Hoch' WHEN SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) >= 50 THEN 'Mittel' ELSE 'Niedrig' END FROM kunden INNER JOIN bestellungen ON kunden.id = bestellungen.kunden_id INNER JOIN bestellpositionen ON bestellungen.id = bestellpositionen.bestellung_id GROUP BY kunden.name;`,
    hint: 'Gruppiere nach kunden.name, summiere menge * einzelpreis und nutze CASE WHEN direkt auf der SUM()-Berechnung.',
    points: 20
  },
  {
    id: 62,
    title: 'Bestellungen nach Wert klassifizieren',
    difficulty: 'Meister',
    topic: 'CASE WHEN',
    explanation: 'CASE WHEN kann auch Bestellungen nach ihrem Gesamtwert bewerten. Die Gruppierung berechnet zuerst den Bestellwert, CASE WHEN gibt danach die passende Kategorie zurück.',
    task: 'Zeige jede Bestellung mit Bestell-ID, Bestelldatum, Bestellwert und Wertklasse: Groß ab 500, Normal ab 50, Klein darunter.',
    expectedSql: `SELECT bestellungen.id, bestellungen.bestelldatum, SUM(bestellpositionen.menge * bestellpositionen.einzelpreis), CASE WHEN SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) >= 500 THEN 'Groß' WHEN SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) >= 50 THEN 'Normal' ELSE 'Klein' END FROM bestellungen INNER JOIN bestellpositionen ON bestellungen.id = bestellpositionen.bestellung_id GROUP BY bestellungen.id, bestellungen.bestelldatum;`,
    hint: 'Verbinde bestellungen mit bestellpositionen, gruppiere nach Bestellung und klassifiziere die Summe mit CASE WHEN.',
    points: 20
  },
  {
    id: 63,
    title: 'Bestellwerte mit WITH vorbereiten',
    difficulty: 'Meister',
    topic: 'CTE / WITH',
    explanation: 'WITH erstellt eine Common Table Expression (CTE): ein benanntes Zwischenergebnis, das die Hauptabfrage übersichtlicher macht. sql.js 1.10.3 basiert auf SQLite mit WITH-Unterstützung.',
    task: 'Berechne zuerst mit WITH den Wert jeder Bestellung. Werte danach aus, wie viele Bestellungen es gibt und wie hoch der durchschnittliche Bestellwert ist.',
    expectedSql: 'WITH bestellwerte AS (SELECT bestellung_id, SUM(menge * einzelpreis) AS bestellwert FROM bestellpositionen GROUP BY bestellung_id) SELECT COUNT(*), AVG(bestellwert) FROM bestellwerte;',
    hint: 'Lege mit WITH bestellwerte AS (...) ein Zwischenergebnis an und nutze es danach wie eine Tabelle.',
    points: 20
  },
  {
    id: 64,
    title: 'Kundenumsätze mit CTE auswerten',
    difficulty: 'Meister',
    topic: 'CTE / WITH',
    explanation: 'CTEs helfen besonders, wenn du einen berechneten Zwischenstand anschließend filtern oder sortieren möchtest.',
    task: 'Berechne mit WITH den Umsatz pro Kunde. Zeige danach nur Kunden, deren Umsatz über dem durchschnittlichen Kundenumsatz liegt.',
    expectedSql: 'WITH kundenumsaetze AS (SELECT kunden.name, SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) AS umsatz FROM kunden INNER JOIN bestellungen ON kunden.id = bestellungen.kunden_id INNER JOIN bestellpositionen ON bestellungen.id = bestellpositionen.bestellung_id GROUP BY kunden.name) SELECT name, umsatz FROM kundenumsaetze WHERE umsatz > (SELECT AVG(umsatz) FROM kundenumsaetze);',
    hint: 'Die CTE liefert name und umsatz. In der Hauptabfrage vergleichst du umsatz mit SELECT AVG(umsatz) FROM kundenumsaetze.',
    points: 20
  },
  {
    id: 65,
    title: 'Kunden über dem Durchschnittsumsatz',
    difficulty: 'Meister',
    topic: 'mehrstufige Unterabfrage',
    explanation: 'Mehrstufige Unterabfragen verschachteln mehrere Auswertungen. Hier vergleichst du gruppierte Kundenumsätze mit einem Durchschnitt aus einer weiteren Gruppierung.',
    task: 'Zeige Kunden und Umsatz, wenn ihr Umsatz höher ist als der durchschnittliche Umsatz aller Kunden mit Bestellung.',
    expectedSql: 'SELECT kunden.name, SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) FROM kunden INNER JOIN bestellungen ON kunden.id = bestellungen.kunden_id INNER JOIN bestellpositionen ON bestellungen.id = bestellpositionen.bestellung_id GROUP BY kunden.name HAVING SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) > (SELECT AVG(umsatz) FROM (SELECT SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) AS umsatz FROM kunden INNER JOIN bestellungen ON kunden.id = bestellungen.kunden_id INNER JOIN bestellpositionen ON bestellungen.id = bestellpositionen.bestellung_id GROUP BY kunden.name));',
    hint: 'Außen gruppierst du pro Kunde. Innen berechnest du ebenfalls Kundenumsätze und bildest daraus AVG(umsatz).',
    points: 20
  },
  {
    id: 66,
    title: 'Ungewöhnlich häufig verkaufte Produkte',
    difficulty: 'Meister',
    topic: 'mehrstufige Unterabfrage',
    explanation: 'Mit HAVING und einer Unterabfrage findest du Gruppen, deren Kennzahl über einem Vergleichswert anderer Gruppen liegt.',
    task: 'Zeige Produkte und verkaufte Gesamtmenge, wenn die Menge höher ist als die durchschnittlich verkaufte Gesamtmenge pro bestelltem Produkt.',
    expectedSql: 'SELECT produkte.name, SUM(bestellpositionen.menge) FROM produkte INNER JOIN bestellpositionen ON produkte.id = bestellpositionen.produkt_id GROUP BY produkte.name HAVING SUM(bestellpositionen.menge) > (SELECT AVG(gesamtmenge) FROM (SELECT SUM(menge) AS gesamtmenge FROM bestellpositionen GROUP BY produkt_id));',
    hint: 'Berechne außen SUM(menge) je Produkt. Die Unterabfrage berechnet erst Gesamtmengen je produkt_id und daraus den Durchschnitt.',
    points: 20
  },
  {
    id: 67,
    title: 'Kunden mit starken Bestellwerten',
    difficulty: 'Meister',
    topic: 'komplexe Aggregation',
    explanation: 'Komplexe JOIN-Auswertungen verbinden mehrere Tabellen, berechnen Werte und filtern Gruppen mit HAVING.',
    task: 'Zeige Kundennamen, Anzahl ihrer Bestellungen und Umsatz. Es sollen nur Kunden mit mindestens zwei Bestellungen und mehr als 100 Umsatz erscheinen.',
    expectedSql: 'SELECT kunden.name, COUNT(DISTINCT bestellungen.id), SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) FROM kunden INNER JOIN bestellungen ON kunden.id = bestellungen.kunden_id INNER JOIN bestellpositionen ON bestellungen.id = bestellpositionen.bestellung_id GROUP BY kunden.name HAVING COUNT(DISTINCT bestellungen.id) >= 2 AND SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) > 100;',
    hint: 'Nutze COUNT(DISTINCT bestellungen.id) für Bestellungen und SUM(menge * einzelpreis) für Umsatz.',
    points: 20
  },
  {
    id: 68,
    title: 'Kategorien mit nennenswertem Umsatz',
    difficulty: 'Meister',
    topic: 'komplexe Aggregation',
    explanation: 'Gruppierungen über Produktkategorien zeigen, welche Bereiche Umsatz und Menge bringen. HAVING blendet kleine Gruppen aus.',
    task: 'Zeige Produktkategorie, verkaufte Menge und Umsatz für Kategorien mit mehr als 50 Umsatz. Sortiere nach Umsatz absteigend.',
    expectedSql: 'SELECT produkte.kategorie, SUM(bestellpositionen.menge), SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) FROM produkte INNER JOIN bestellpositionen ON produkte.id = bestellpositionen.produkt_id GROUP BY produkte.kategorie HAVING SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) > 50 ORDER BY SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) DESC;',
    hint: 'Verbinde produkte mit bestellpositionen, gruppiere nach kategorie und filtere den Umsatz mit HAVING.',
    points: 20
  },
  {
    id: 69,
    title: 'Meister-Challenge Kundenwert',
    difficulty: 'Meister',
    topic: 'Meister-Auswertung',
    explanation: 'Diese Challenge verbindet JOIN, CTE, CASE WHEN, GROUP BY, HAVING und AVG. Du bereitest Kundenumsätze vor und bewertest sie im Vergleich zum Durchschnitt.',
    task: 'Berechne mit WITH den Umsatz pro Kunde. Zeige Kunden mit Umsatz über 50 und ordne sie im Vergleich zum durchschnittlichen Kundenumsatz als Über Durchschnitt oder Im Durchschnitt ein.',
    expectedSql: `WITH kundenumsaetze AS (SELECT kunden.name, SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) AS umsatz FROM kunden INNER JOIN bestellungen ON kunden.id = bestellungen.kunden_id INNER JOIN bestellpositionen ON bestellungen.id = bestellpositionen.bestellung_id GROUP BY kunden.name) SELECT name, umsatz, CASE WHEN umsatz > (SELECT AVG(umsatz) FROM kundenumsaetze) THEN 'Über Durchschnitt' ELSE 'Im Durchschnitt' END FROM kundenumsaetze WHERE umsatz > 50;`,
    hint: 'Die CTE liefert alle Kundenumsätze. Danach nutzt du CASE WHEN und eine AVG-Unterabfrage auf derselben CTE.',
    points: 25
  },
  {
    id: 70,
    title: 'Meister-Challenge Produktperformance',
    difficulty: 'Meister',
    topic: 'Meister-Auswertung',
    explanation: 'Die Abschlussaufgabe kombiniert eine Unterabfrage, mehrere JOIN-Bausteine, CASE WHEN, GROUP BY, HAVING, SUM und eine Umsatzberechnung.',
    task: 'Zeige Produktname, Kategorie, verkaufte Menge, Umsatz und Performance. Produkte mit Umsatz über dem durchschnittlichen Produktumsatz heißen Stark, alle anderen Normal. Zeige nur Produkte mit mindestens 2 verkauften Stück.',
    expectedSql: `SELECT produkte.name, produkte.kategorie, SUM(bestellpositionen.menge), SUM(bestellpositionen.menge * bestellpositionen.einzelpreis), CASE WHEN SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) > (SELECT AVG(produktumsatz) FROM (SELECT SUM(menge * einzelpreis) AS produktumsatz FROM bestellpositionen GROUP BY produkt_id)) THEN 'Stark' ELSE 'Normal' END FROM produkte INNER JOIN bestellpositionen ON produkte.id = bestellpositionen.produkt_id GROUP BY produkte.name, produkte.kategorie HAVING SUM(bestellpositionen.menge) >= 2;`,
    hint: 'Außen gruppierst du pro Produkt. Im CASE WHEN vergleichst du den Produktumsatz mit dem Durchschnitt der gruppierten Produktumsätze.',
    points: 25

  },
  {
    id: 71,
    title: 'Fehlende Bestellungen lesbar anzeigen',
    difficulty: 'Meister',
    topic: 'NULL und COALESCE',
    explanation: 'LEFT JOIN kann fehlende Werte erzeugen: Kunden ohne Bestellung haben dann NULL in den Bestellspalten. COALESCE() ersetzt NULL durch einen sinnvollen Text, ohne echte vorhandene Werte zu verändern.',
    task: 'Zeige alle Kundennamen und den Bestellstatus. Kunden ohne Bestellung sollen beim Status den Text Keine Bestellung anzeigen.',
    expectedSql: `SELECT kunden.name, COALESCE(bestellungen.status, 'Keine Bestellung') FROM kunden LEFT JOIN bestellungen ON kunden.id = bestellungen.kunden_id;`,
    hint: `Nutze LEFT JOIN, damit auch Kunden ohne Bestellung erscheinen. COALESCE(bestellungen.status, 'Keine Bestellung') ersetzt nur fehlende Statuswerte.`,
    points: 20
  },
  {
    id: 72,
    title: 'Kennzahlen gegen NULL absichern',
    difficulty: 'Meister',
    topic: 'COALESCE bei Aggregaten',
    explanation: 'SUM() liefert bei fehlenden passenden Zeilen NULL. Mit COALESCE(SUM(...), 0) wird daraus ein echter Zahlenwert 0. So unterscheidest du fehlende Umsätze sauber von vorhandenen Umsätzen.',
    task: 'Zeige alle Kundennamen und ihren Umsatz. Kunden ohne Bestellung sollen den Umsatz 0 erhalten. Sortiere nach Umsatz absteigend.',
    expectedSql: 'SELECT kunden.name, COALESCE(SUM(bestellpositionen.menge * bestellpositionen.einzelpreis), 0) FROM kunden LEFT JOIN bestellungen ON kunden.id = bestellungen.kunden_id LEFT JOIN bestellpositionen ON bestellungen.id = bestellpositionen.bestellung_id GROUP BY kunden.name ORDER BY COALESCE(SUM(bestellpositionen.menge * bestellpositionen.einzelpreis), 0) DESC;',
    hint: 'Nutze zwei LEFT JOINs und sichere die SUM()-Berechnung mit COALESCE(..., 0) ab.',
    points: 20
  },
  {
    id: 73,
    title: 'Bestellungen pro Monat zählen',
    difficulty: 'Meister',
    topic: 'Datumsfunktionen',
    explanation: `SQLite kann Textdaten im ISO-Format mit strftime('%Y-%m', bestelldatum) auswerten. Das erzeugt einen Monatsschlüssel wie 2026-01.`,
    task: 'Zähle die Bestellungen pro Monat. Zeige Monat und Bestellanzahl, sortiert nach Monat.',
    expectedSql: `SELECT strftime('%Y-%m', bestelldatum), COUNT(*) FROM bestellungen GROUP BY strftime('%Y-%m', bestelldatum) ORDER BY strftime('%Y-%m', bestelldatum);`,
    hint: `Gruppiere und sortiere nach demselben strftime('%Y-%m', bestelldatum)-Ausdruck.`,
    points: 20
  },
  {
    id: 74,
    title: 'Monatsumsatz im Jahr 2026',
    difficulty: 'Meister',
    topic: 'date() und strftime()',
    explanation: `date() normalisiert Datumswerte, strftime('%Y', ...) filtert nach Jahr und strftime('%Y-%m', ...) gruppiert nach Monat.`,
    task: 'Berechne den Umsatz pro Monat für Bestellungen aus dem Jahr 2026. Zeige Monat und Umsatz, sortiert nach Monat.',
    expectedSql: `SELECT strftime('%Y-%m', date(bestellungen.bestelldatum)), SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) FROM bestellungen INNER JOIN bestellpositionen ON bestellungen.id = bestellpositionen.bestellung_id WHERE strftime('%Y', date(bestellungen.bestelldatum)) = '2026' GROUP BY strftime('%Y-%m', date(bestellungen.bestelldatum)) ORDER BY strftime('%Y-%m', date(bestellungen.bestelldatum));`,
    hint: `Verbinde Bestellungen mit Positionen, filtere das Jahr mit strftime('%Y', date(...)) und gruppiere nach strftime('%Y-%m', date(...)).`,
    points: 20
  },
  {
    id: 75,
    title: 'Produkte eindeutig nach Preis nummerieren',
    difficulty: 'Meister',
    topic: 'ROW_NUMBER()',
    explanation: 'Window Functions funktionieren in der verwendeten sql.js-Version 1.10.3, die auf einer SQLite-Version mit Fensterfunktionen basiert. ROW_NUMBER() vergibt eine eindeutige laufende Nummer gemäß ORDER BY innerhalb von OVER().',
    task: 'Zeige Produktname, Preis und eine eindeutige Preisnummer. Das teuerste Produkt soll Nummer 1 erhalten.',
    expectedSql: 'SELECT name, preis, ROW_NUMBER() OVER (ORDER BY preis DESC) FROM produkte;',
    hint: 'Nutze ROW_NUMBER() OVER (ORDER BY preis DESC).',
    points: 20
  },
  {
    id: 76,
    title: 'Kunden nach Punkten ranken',
    difficulty: 'Meister',
    topic: 'RANK()',
    explanation: 'RANK() erstellt eine Rangliste. Gleiche Werte erhalten denselben Rang; danach kann eine Rangnummer übersprungen werden. Das ORDER BY steht innerhalb von OVER().',
    task: 'Zeige Kundennamen, Punkte und ihren Punkterang. Die meisten Punkte sollen Rang 1 erhalten.',
    expectedSql: 'SELECT name, punkte, RANK() OVER (ORDER BY punkte DESC) FROM kunden;',
    hint: 'Nutze RANK() OVER (ORDER BY punkte DESC).',
    points: 20
  },
  {
    id: 77,
    title: 'Produkte innerhalb der Kategorie ranken',
    difficulty: 'Meister',
    topic: 'PARTITION BY',
    explanation: 'PARTITION BY teilt eine Window Function in Gruppen auf. Der Rang beginnt dadurch in jeder Kategorie neu.',
    task: 'Zeige Kategorie, Produktname, Preis und den Preisrang innerhalb der jeweiligen Kategorie. Das teuerste Produkt jeder Kategorie soll Rang 1 erhalten.',
    expectedSql: 'SELECT kategorie, name, preis, RANK() OVER (PARTITION BY kategorie ORDER BY preis DESC) FROM produkte;',
    hint: 'PARTITION BY kategorie trennt die Rangliste je Kategorie; ORDER BY preis DESC sortiert innerhalb der Kategorie.',
    points: 20
  },
  {
    id: 78,
    title: 'Laufenden Umsatz berechnen',
    difficulty: 'Meister',
    topic: 'laufende Summen',
    explanation: 'Mit SUM(...) OVER (ORDER BY ...) berechnest du laufende Werte. Jede Zeile enthält dann die Summe bis zur aktuellen Zeile in der angegebenen Sortierung.',
    task: 'Berechne mit WITH zuerst den Wert jeder Bestellung. Zeige danach Bestell-ID, Bestelldatum, Bestellwert und den laufenden Umsatz nach Bestelldatum und Bestell-ID.',
    expectedSql: 'WITH bestellwerte AS (SELECT bestellungen.id, bestellungen.bestelldatum, SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) AS bestellwert FROM bestellungen INNER JOIN bestellpositionen ON bestellungen.id = bestellpositionen.bestellung_id GROUP BY bestellungen.id, bestellungen.bestelldatum) SELECT id, bestelldatum, bestellwert, SUM(bestellwert) OVER (ORDER BY bestelldatum, id) FROM bestellwerte;',
    hint: 'Die CTE berechnet bestellwert je Bestellung. Danach nutzt du SUM(bestellwert) OVER (ORDER BY bestelldatum, id).',
    points: 20
  },
  {
    id: 79,
    title: 'Meister-Challenge Kundenranking',
    difficulty: 'Meister',
    topic: 'JOIN + COALESCE + Window Function',
    explanation: 'Diese Challenge kombiniert LEFT JOIN, COALESCE, GROUP BY, CASE WHEN und RANK(). Eine CTE macht die Kundenumsätze wiederverwendbar.',
    task: 'Berechne mit WITH für jeden Kunden den Umsatz, auch wenn keine Bestellung vorhanden ist. Zeige Name, Stadt, Umsatz, Kundenklasse Aktiv ab 50 Umsatz sonst Beobachten und den Umsatzrang. Sortiere nach Rang.',
    expectedSql: `WITH kundenwerte AS (SELECT kunden.name, kunden.stadt, COALESCE(SUM(bestellpositionen.menge * bestellpositionen.einzelpreis), 0) AS umsatz FROM kunden LEFT JOIN bestellungen ON kunden.id = bestellungen.kunden_id LEFT JOIN bestellpositionen ON bestellungen.id = bestellpositionen.bestellung_id GROUP BY kunden.name, kunden.stadt) SELECT name, stadt, umsatz, CASE WHEN umsatz >= 50 THEN 'Aktiv' ELSE 'Beobachten' END, RANK() OVER (ORDER BY umsatz DESC) FROM kundenwerte ORDER BY RANK() OVER (ORDER BY umsatz DESC);`,
    hint: 'Bereite Umsatz mit COALESCE in einer CTE vor. In der Hauptabfrage nutzt du CASE WHEN und RANK() OVER (ORDER BY umsatz DESC).',
    points: 25
  },
  {
    id: 80,
    title: 'Meister-Challenge Monats- und Kategorieanalyse',
    difficulty: 'Meister',
    topic: 'CTE + PARTITION BY',
    explanation: 'Die finale Challenge verbindet Datumsfunktionen, JOIN, GROUP BY, HAVING, CTE, CASE WHEN und Window Functions mit PARTITION BY.',
    task: 'Berechne mit WITH den Umsatz pro Monat und Produktkategorie. Zeige Monat, Kategorie, Umsatz, Monatsrang innerhalb des Monats und Bewertung Stark ab 50 Umsatz sonst Normal. Es sollen nur Gruppen mit mindestens 2 verkauften Stück erscheinen. Sortiere nach Monat und Rang.',
    expectedSql: `WITH monatskategorien AS (SELECT strftime('%Y-%m', bestellungen.bestelldatum) AS monat, produkte.kategorie, SUM(bestellpositionen.menge) AS menge, SUM(bestellpositionen.menge * bestellpositionen.einzelpreis) AS umsatz FROM bestellungen INNER JOIN bestellpositionen ON bestellungen.id = bestellpositionen.bestellung_id INNER JOIN produkte ON bestellpositionen.produkt_id = produkte.id GROUP BY strftime('%Y-%m', bestellungen.bestelldatum), produkte.kategorie HAVING SUM(bestellpositionen.menge) >= 2) SELECT monat, kategorie, umsatz, RANK() OVER (PARTITION BY monat ORDER BY umsatz DESC), CASE WHEN umsatz >= 50 THEN 'Stark' ELSE 'Normal' END FROM monatskategorien ORDER BY monat, RANK() OVER (PARTITION BY monat ORDER BY umsatz DESC);`,
    hint: 'Gruppiere in der CTE nach Monat und Kategorie. In der Hauptabfrage rankst du mit RANK() OVER (PARTITION BY monat ORDER BY umsatz DESC).',
    points: 25
  }


];
